<?php
return [
    'location_route_prefix' => env("LOCATION_ROUTER_PREFIX","location"),

    /*
    | Map location names (lowercase) to ISO 3166-1 alpha-2 country codes when the
    | location is a city/region rather than a country name.
    */
    'region_country_map' => [
        'paris' => 'fr',
        'london' => 'gb',
        'california' => 'us',
        'los angeles' => 'us',
        'new jersey' => 'us',
        'san francisco' => 'us',
        'virginia' => 'us',
        'florida' => 'us',
        'goa' => 'in',
        'munnar' => 'in',
        'shimla' => 'in',
        'delhi' => 'in',
        'agra' => 'in',
        'jaipur' => 'in',
        'rajasthan' => 'in',
        'ujain' => 'in',
        'haridwar' => 'in',
        'rshikesh' => 'in',
        'kashmeer' => 'in',
        'amritsar' => 'in',
        'vga border' => 'in',
        'ahamadabad' => 'in',
        'trivandrum' => 'in',
        'ernakulam' => 'in',
        'palakkad' => 'in',
        'tamilnadu' => 'in',
        'andrapradesh' => 'in',
        'maharastra' => 'in',
        'thrissur' => 'in',
        'kerala' => 'in',
        'meghalaya' => 'in',
        'himachal pradesh' => 'in',
        'ladakh' => 'in',
        'sikkim' => 'in',
        'karnataka' => 'in',
        'madikeri' => 'in',
        'kunnamkulam' => 'in',
        'vagamon' => 'in',
        'hampi' => 'in',
        'varanasi' => 'in',
        'andaman' => 'in',
        'odisha' => 'in',
        'wayanad' => 'in',
        'haryana' => 'in',
        'hydrabad' => 'in',
        'uttarakhand' => 'in',
        'kalathilpadi' => 'in',
        'adimali' => 'in',
        'bagdogra' => 'in',
        'lakshadweep' => 'in',
        'dubai' => 'ae',
        'sharja' => 'ae',
        'abhudhabi' => 'ae',
        'salalah' => 'om',
        'bali' => 'id',
        'bangkok' => 'th',
        'bankok' => 'th',
        'pattaya' => 'th',
        'colombo' => 'lk',
        'nigambo' => 'lk',
        'candy' => 'lk',
        'sigiriya' => 'lk',
        'chitwan' => 'np',
        'jerusalem' => 'il',
        'goergea' => 'ge',
        'kolhapur malaysia' => 'my',
    ],
];